AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  FHIR validator lambda

Parameters:
  LogLevel:
    Type: String
    Description: The log level to set in the lambda
    Default: "INFO"
  LogRetentionDays:
    Type: Number
    Description: How long to keep logs for
    Default: 30
    AllowedValues:
      [
        1,
        3,
        5,
        7,
        14,
        30,
        60,
        90,
        120,
        150,
        180,
        365,
        400,
        545,
        731,
        1096,
        1827,
        2192,
        2557,
        2922,
        3288,
        3653,
      ]

Resources:
  FHIRValidatorResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: lambda_resources.yaml
      Parameters:
        CloudWatchKMSKey: !ImportValue account-resources:CloudwatchLogsKmsKeyArn
        SplunkSubscriptionFilterRole: !ImportValue lambda-resources:SplunkSubscriptionFilterRole
        SplunkDeliveryStream: !ImportValue lambda-resources:SplunkDeliveryStream
        EnableSplunk: "true"
        LambdaName: !Sub "${AWS::StackName}-FHIRValidator"
        LogRetentionDays: !Ref LogRetentionDays

  FHIRValidator:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-FHIRValidator"
      CodeUri: ../
      Handler: software.nhs.FHIRValidator.HandlerStream::handleRequest
      Role: !GetAtt FHIRValidatorResources.Outputs.LambdaRoleArn
      SnapStart:
        ApplyOn: PublishedVersions
      AutoPublishAlias: snap
      Timeout: 600
      MemorySize: 4096
      Architectures:
        - x86_64
      Runtime: java21
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:38"
      Environment:
        Variables:
          AWS_LAMBDA_LOG_LEVEL: !Ref LogLevel
          POWERTOOLS_LOG_LEVEL: !Ref LogLevel

Outputs:
  FHIRValidatorLambdaName:
    Description: Name of the FHIR validator lambda
    Value: !Ref FHIRValidator
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FHIRValidatorLambdaName"]]
  FHIRValidatorLambdaArn:
    Description: Arn of the FHIR validator lambda
    Value: !GetAtt FHIRValidator.Arn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "FHIRValidatorLambdaArn"]]
